# Generated by Django 4.0.3 on 2022-06-08 21:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0009_recipe_author'),
        ('mealplans', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meal_plan',
            new_name='Mealplan',
        ),
    ]
