# Generated by Django 4.0.3 on 2022-06-09 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplans', '0003_alter_mealplan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='date',
            field=models.DateField(),
        ),
    ]
